import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ToastContainer } from "react-toastify";
import { ThemeInitializer } from "@/src/components/shared/Theme";
import { MainLayout } from "@/src/components/shared/Layouts/Main";
import { Header } from "@/src/components/shared/Header";
import { Footer } from "@/src/components/shared/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps { children: React.ReactNode; cookies?: string; }

function getThemeFromCookie(cookie?: string): 'light' | 'dark' {
  if (!cookie) return 'light';
  const match = cookie.match(/theme=(dark|light)/);
  return match ? (match[1] as 'light' | 'dark') : 'light';
}

export default function RootLayout({ children, cookies }: RootLayoutProps) {
  const theme = getThemeFromCookie(cookies);
  return (
    <html lang="pt-BR">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased ${theme === 'dark' ? 'dark' : ''}`} data-testid="root-layout">
        <ThemeInitializer />
        <MainLayout>
          <Header />
          <ToastContainer className="bg-gray-100" />
          {children}
          <Footer />
        </MainLayout>
      </body>
    </html>
  );
}
