import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ThemeInitializer } from "@/components/shared/Theme";
import { MenuProvider } from "@/contexts/manager_context";
import { ManagerLayout } from "@/components/shared/Layouts/Manager";
import { ToastContainer } from "react-toastify";
import { Header } from "@/components/shared/Header";
import { MenuAside } from "@/components/shared/MenuAside";
import { LayoutCaptureError } from "@/components/shared/Layouts/Manager/layer_cap_error";
import { Footer } from "@/components/shared/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps { children: React.ReactNode; cookies?: string; };
function getThemeFromCookie(cookie?: string): 'light' | 'dark' {
  if (!cookie) return 'light';
  const match = cookie.match(/theme=(dark|light)/);
  return match ? (match[1] as 'light' | 'dark') : 'light';
};

export default function RootLayout({ children, cookies }: RootLayoutProps) {
  const theme = getThemeFromCookie(cookies);

  return (
    <html lang="pt-BR">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased ${theme === 'dark' ? 'dark' : ''}`} data-testid="root-layout">
        <ThemeInitializer />

        <MenuProvider>
          <ManagerLayout>
            <Header />
            <ToastContainer className="bg-gray-100" />
            <MenuAside />
            <LayoutCaptureError>
              {children}
            </LayoutCaptureError>
            <Footer />
          </ManagerLayout>
        </MenuProvider>

      </body>
    </html>
  );
}
